# jekyll configuration

title: "ALMighty-devdoc"

collections:
  blueprints:
    output: true

asciidoctor:
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

defaults:
  - scope:
      path: ""
      type: blueprints
    values:
      layout: blueprint

# When building in Jenkins, this is where the Gems are installed
# and we don't want them to be checked
exclude: [bundle-install]

# end of configuration
